@startuml
participant actor as 0
participant OkHttpClient.Builder as b
participant OkHttpClient as a
participant RealCall as c
participant RealInterceptorChain as d
participant RetryAndFollowUpInterceptor as e
participant BridgeInterceptor as f
participant CacheInterceptor as g
participant ConnectInterceptor as h
participant CallServerInterceptor as i

0 -> b : new OkHttpClient.Builder()
activate b
b -> b : build()
return a
0 -> a : newCall(request)
a -> c : newRealCall()
c -> c : RealCall.<init>()
activate c
c -> 0 : RealCall
0 -> c : execute()
c -> c : getResponseWithInterceptorChain()
c -> e : RetryAndFollowUpInterceptor.<init>()
activate e
c -> f : BridgeInterceptor.<init>()
activate f
c -> g : CacheInterceptor.<init>()
activate g
c -> h : ConnectInterceptor.<init>()
activate h
c -> i : CallServerInterceptor.<init>()
activate i
c -> d : RealInterceptorChain.<init>()
activate d
c -> d : proceed()
d -> e : intercept()
e -> f : intercept()
f -> g : intercept()
g -> h : intercept()
h -> i : intercept()
i --> h : Response
deactivate i
h --> g : Response
deactivate h
g --> f : Response
deactivate g
f --> e : Response
deactivate f
e --> d : Response
deactivate e
d --> c : Response
deactivate d
c --> 0 : Response

@enduml
