@startuml
abstract class SettingBase {
    ~ int pkgFlags
    ~ int pkgPrivateFlags
}
abstract class PackageSettingBase {
    + String name
    ~ String realName
    ~ File codePath
    ~ String codePathString
    ~ File resourcePath
    ~ String resourcePathString
    ~ String[] usesStaticLibraries
    ~ long[] usesStaticLibrariesVersions
    ~ String legacyNativeLibraryPathString
    + String primaryCpuAbiString
    + String secondaryCpuAbiString
    ~ String cpuAbiOverrideString
    ~ long timeStamp
    ~ long firstInstallTime
    ~ long lastUpdateTime
    ~ long versionCode
    ~ boolean uidError
    ~ PackageSignatures signatures
    ~ boolean installPermissionsFixed
}
class PackageSetting {
    ~ int appId
    + AndroidPackage pkg
    ~ SharedUserSetting sharedUser
    - int sharedUserId
    ~ Map<String, ArraySet<String>> mimeGroups
    - PackageStateUnserialized pkgState
}
SettingBase <|-- PackageSettingBase
PackageSettingBase <|-- PackageSetting

@enduml
